language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery.py .
branches:
  only:
  - master
after_script:
- rm -rf builds/build/sources builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH bakery-report.py builds/build
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH travis-deploy.py
env:
  global:
    secure: M0S+GYTM+07PijgQix31RSv+35EsR6c3OVeWhEtxtjEgrDNuZGy8sSJ8TvlqpU+YUtZ61t9naugn6Pj//7OuiknUxibbvfdkFM1jxNEfIQCuZjZGoDOltjDYo3I4XeQwnATUlDLw+XOVP5r6mn3iJmsWtjTedll4uLe2c3NzLMM=
